services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mnist-api
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: mnist-frontend
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    restart: unless-stopped